### ISSUE TITLE
Absolute Timestamps available in python? 

### ISSUE THREAD

**Issue by JamaicanFriedChicken** [george-hawkins/gst-absolutetimestamps#1]
Hey George, I would like to ask if it was possible you'd have a python version of this code.

**Comment by george-hawkins** [comment]
Hello Mickey - I don't have a Python version of this code. As to your other question about meta-data - I'm very new to GStreamer so I'm probably not the best person to ask.

I don't know of a specific GStreamer element to do this, there are sections in the GStreamer tutorial on gathering metadata, e.g. [here](https://gstreamer.freedesktop.org/documentation/application-development/advanced/metadata.html) and [here](https://gstreamer.freedesktop.org/documentation/tutorials/basic/media-information-gathering.html), but these involve writing code.

You can get a GStreamer pipeline to dump out an awful lot of information, when it runs, using [`GST_DEBUG`](https://gstreamer.freedesktop.org/documentation/tutorials/basic/debugging-tools.html) and it may be possible to get the information you want this way.

**Comment by JamaicanFriedChicken** [comment]
Sorry George, I just realized that I could have installed your plugin and then just use it in the pipeline instead of trying to write some code. Then just read it from the logs file your script creates. My bad, I need to be more aware. Thanks a lot! I appreciate it. One more question, I got to ask though, if i were to make a plugin like you did specifically for the metadata in C, would I have to install it as well just to use it in the gstreamer pipeline? 

Edit: I have just tried your plugin, using this pipeline:

```
rtspsrc location=rtsp://admin:password@192.168.1.65:554 drop-on-latency=0 latency=10 !
rtph264depay ! h264parse ! decodebin ! videoconvert! videoscale !
video/x-raw, format=(string)BGR, width=(int){}, height=(int){},
framerate=25/1 ! timeoverlay halignment=left valignment=bottom text ="Stream time:" 
font-desc="Sans, 20"! clockoverlay ! absolutetimestamps ! 
videoconvert ! appsink emit-signals=true sync=true max-buffers=3 drop=false
```
It's great except the timestamps it prints into the logs is a bit behind. At the moment its 17:32 where I am `0:01:18.660539808 2019-08-08T10:32:26.321259Z` but i got 10:32. Could it be because of another plugin in the pipeline or because I didn't include `num-buffers ` or set `framerate=24/1`. Will continue to play with it a bit.

**Comment by george-hawkins** [comment]
I think we're two GStreamer beginners talking to each other, so my advice may not be worth a lot.

I can't try out your pipeline at the moment - I'm not really sure what you're issue is. If it's simply that the hour is "wrong", i.e. you see 10:32 in the logs but it's 17:32 where you are, then I assume this is simply a time zone issue - i.e. you're somewhere, like e.g. Jakarta, that's 7 hours ahead of [UTC](https://en.wikipedia.org/wiki/Coordinated_Universal_Time) (the "Z" at the end of the time value indicates UTC). To handle this you'll need to look into time zone handling in Python and covert back and forward between your local time and UTC to deal with the difference in time zones involved.

**Comment by JamaicanFriedChicken** [comment]
No, you're advice is very much appreciated. Thank you. I have considered that would be the case that the time zone needs to be adjusted to resolve the difference but it's a very small issue. Nothing big. 
The `absolutetimestamp` plugin you made (which I am forever grateful for!) only writes the real world timestamp to the log, might I ask what did you use to actually get the offset time i.e. the actual time the camera starts recording to calculate the `absolutetimestamp`. I have noticed the first timestamp the plugin begins to write in the log actually doesn't correlate to the time it began (sorry, I am a bit slow. Please forgive me).
I wanted to ask once I have the offset time and the timestamp from the log, wouldn't I just be able to calculate the delay? I am using multiple network cameras and trying to sync them using the timestamps, a bit difficult for me at the moment.
